### PR TITLE
Expose OpenSSL.Session internal types

### PR DESCRIPTION
**Pull request by glguy**
Fixes #61

### CODE REVIEW

**Comment by vshabanov** [comment]
Just a thought. Since you need it to add some functionality to HsOpenSSL (https://github.com/phonohawk/HsOpenSSL/issues/59), maybe it's better to add this functionality directly without exposing internals? I would better accept a pull request with those 3 functions needed in Session.hsc (like I did myself in https://github.com/vshabanov/HsOpenSSL/commit/79c7b4c343729570f4736a66a9bf262069f37922).

**Comment by glguy** [comment]
Until the binding is complete it should expose the openSSL objects. This package isn't abstracting the notion openssl, it's a binding to a well known library with a stable api. Hiding these details gains nothing and impedes usage.

**Comment by glguy** [comment]
Thanks for merging this. My concern with these new bindings is that they are new to Open SSL 1.0.2. Is this too recent of a requirement for HsOpennSSL itself?

**Comment by vshabanov** [comment]
Fair enough. Although it would be nice if you could make a pull request with functions you need to make bindings more complete.

**Comment by vshabanov** [comment]
Look at my commit https://github.com/vshabanov/HsOpenSSL/commit/79c7b4c343729570f4736a66a9bf262069f37922#diff-0ae2970018a84154878783da2d12fc1bR287
I have a check on a C side for this function. Although it would be better to do this in .hsc file itself.
So with some `#ifdef` it should be possible to add it to the library.

**Pull request merged**
