### PR TITLE
Declare pkg-config dependencies

### PR DESCRIPTION
**Pull request by osa1**

### CODE REVIEW

**Comment by vshabanov** [comment]
It fails Travis CI (for some reason Cabal 2.5 can't parse output of `pkg-config --modversion`) and not all systems have `pkg-config` so it's necessary to take it into account somehow.

Do you really need `pkg-config`? HsOpenSSL has a lot of options for various platforms and even tries autodetect OpenSSL installation path on macOS.

**Comment by osa1** [comment]
Thanks for the quick response.

I have no idea if I absolutely need this, but this was needed to make this package buildable on NixOS. Maybe @bgamari can provide more info on this as he suggested me adding this field.

**Comment by osa1** [comment]
Just confirmed with @phadej that the `pkg-config --modversions` parsing problem is a Cabal bug and it now fixed in https://github.com/haskell/cabal/issues/163 .

It'll take some time for that change to be shipped though.

**Comment by vshabanov** [comment]
Great. It seems that following scheme is used in tests related to fix:

```
Flag use-pkg-config
    default: False
    manual:  True
...
Library
    ...
    if flag(use-pkg-config)
        pkgconfig-depends: ...
    else
        ...
```

Perhaps it worth to adopt it so `HsOpenSSL` could be used on all systems with or without pkg-config

**Comment by vshabanov** [comment]
Closing this PR, since #51 was merged.

**Pull request closed without merging**
